# Generated by Django 4.0.4 on 2022-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nickname',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='surname',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='name3',
        ),
        migrations.AlterField(
            model_name='pushup',
            name='date',
            field=models.DateTimeField(max_length=30),
        ),
    ]
