# Generated by Django 4.0.4 on 2022-05-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_nickname_person_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushup',
            name='pushups',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
