# Generated by Django 4.0.4 on 2022-05-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pushup_pushups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushup',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
