# Generated by Django 4.0.4 on 2022-05-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pushup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name1',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name2',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name3',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pushup',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pushup',
            name='pushups',
            field=models.IntegerField(default=0),
        ),
    ]
