# Generated by Django 4.0.4 on 2022-05-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name1_person_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushup',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
