# Generated by Django 4.0.4 on 2022-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pushup',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
