# Generated by Django 4.0.4 on 2022-06-13 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_person_nickname_alter_pushup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushup',
            name='pushups',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
